/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as GiveSlugRouteImport } from './routes/give.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app/campaigns'
import { Route as AuthenticatedAppDonationsRouteImport } from './routes/_authenticated/app/donations'
import { Route as AuthenticatedAppDonorsRouteImport } from './routes/_authenticated/app/donors'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app/reports'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app/team'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app/admin'
import { Route as AuthenticatedMyGivingRouteImport } from './routes/_authenticated/my-giving'
import { Route as AuthenticatedAppQrRouteImport } from './routes/_authenticated/app/qr'
import { Route as AuthenticatedAppEmailRouteImport } from './routes/_authenticated/app/email'
import { Route as AuthenticatedAppApiRouteImport } from './routes/_authenticated/app/api'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GiveSlugRoute = GiveSlugRouteImport.update({
  id: '/give/$slug',
  path: '/give/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDonationsRoute =
  AuthenticatedAppDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDonorsRoute = AuthenticatedAppDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedMyGivingRoute = AuthenticatedMyGivingRouteImport.update({
  id: '/my-giving',
  path: '/my-giving',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppQrRoute = AuthenticatedAppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppEmailRoute = AuthenticatedAppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppApiRoute = AuthenticatedAppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/give/$slug': typeof GiveSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/my-giving': typeof AuthenticatedMyGivingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/donations': typeof AuthenticatedAppDonationsRoute
  '/app/donors': typeof AuthenticatedAppDonorsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/app/email': typeof AuthenticatedAppEmailRoute
  '/app/api': typeof AuthenticatedAppApiRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/give/$slug': typeof GiveSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/my-giving': typeof AuthenticatedMyGivingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/donations': typeof AuthenticatedAppDonationsRoute
  '/app/donors': typeof AuthenticatedAppDonorsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/qr': typeof AuthenticatedAppQrRoute
  '/app/email': typeof AuthenticatedAppEmailRoute
  '/app/api': typeof AuthenticatedAppApiRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/give/$slug': typeof GiveSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/my-giving': typeof AuthenticatedMyGivingRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/donations': typeof AuthenticatedAppDonationsRoute
  '/_authenticated/app/donors': typeof AuthenticatedAppDonorsRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/qr': typeof AuthenticatedAppQrRoute
  '/_authenticated/app/email': typeof AuthenticatedAppEmailRoute
  '/_authenticated/app/api': typeof AuthenticatedAppApiRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/app'
    | '/give/$slug'
    | '/invite/$token'
    | '/my-giving'
    | '/app/campaigns'
    | '/app/donations'
    | '/app/donors'
    | '/app/reports'
    | '/app/team'
    | '/app/settings'
    | '/app/admin'
    | '/app/qr'
    | '/app/email'
    | '/app/api'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/give/$slug'
    | '/invite/$token'
    | '/my-giving'
    | '/app/campaigns'
    | '/app/donations'
    | '/app/donors'
    | '/app/reports'
    | '/app/team'
    | '/app/settings'
    | '/app/admin'
    | '/app/qr'
    | '/app/email'
    | '/app/api'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/_authenticated/app'
    | '/give/$slug'
    | '/invite/$token'
    | '/_authenticated/my-giving'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/donations'
    | '/_authenticated/app/donors'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/team'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/qr'
    | '/_authenticated/app/email'
    | '/_authenticated/app/api'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  GiveSlugRoute: typeof GiveSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/give/$slug': {
      id: '/give/$slug'
      path: '/give/$slug'
      fullPath: '/give/$slug'
      preLoaderRoute: typeof GiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/donations': {
      id: '/_authenticated/app/donations'
      path: '/donations'
      fullPath: '/app/donations'
      preLoaderRoute: typeof AuthenticatedAppDonationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/donors': {
      id: '/_authenticated/app/donors'
      path: '/donors'
      fullPath: '/app/donors'
      preLoaderRoute: typeof AuthenticatedAppDonorsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/qr': {
      id: '/_authenticated/app/qr'
      path: '/qr'
      fullPath: '/app/qr'
      preLoaderRoute: typeof AuthenticatedAppQrRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/email': {
      id: '/_authenticated/app/email'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AuthenticatedAppEmailRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/api': {
      id: '/_authenticated/app/api'
      path: '/api'
      fullPath: '/app/api'
      preLoaderRoute: typeof AuthenticatedAppApiRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/my-giving': {
      id: '/_authenticated/my-giving'
      path: '/my-giving'
      fullPath: '/my-giving'
      preLoaderRoute: typeof AuthenticatedMyGivingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppDonationsRoute: typeof AuthenticatedAppDonationsRoute
  AuthenticatedAppDonorsRoute: typeof AuthenticatedAppDonorsRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppQrRoute: typeof AuthenticatedAppQrRoute
  AuthenticatedAppEmailRoute: typeof AuthenticatedAppEmailRoute
  AuthenticatedAppApiRoute: typeof AuthenticatedAppApiRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppDonationsRoute: AuthenticatedAppDonationsRoute,
  AuthenticatedAppDonorsRoute: AuthenticatedAppDonorsRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppQrRoute: AuthenticatedAppQrRoute,
  AuthenticatedAppEmailRoute: AuthenticatedAppEmailRoute,
  AuthenticatedAppApiRoute: AuthenticatedAppApiRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedMyGivingRoute: typeof AuthenticatedMyGivingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedMyGivingRoute: AuthenticatedMyGivingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  GiveSlugRoute: GiveSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
